name: 'WhiteWolf Marketing & Design'
favicon: null
layout_spectrum: 0.44998
typography_spectrum: 0.99741
title: Web Design made simple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#241f25'
    - '#b8b8ba'
    - '#f6f7fb'
    - '#585254'
    - '#7a7375'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
